### PR TITLE
WebUI/Flow: Play timeline button + highlight flows when hovering timeline

### PR DESCRIPTION
**Pull request by fmonjalet**
A bit of refactoring, too.

Ready to merge, although one known bug remains (see FIXME in the diff).

### CODE REVIEW

**Comment by p-l-** [comment]
Awesome, Florent!

A couple of questions:
  - how do i stop the play timeline? (clicking play again replays the timeline from the beginning)
  -  don't you think it would be nice to highlight the current time slot in the timeline while playing it?

**Comment by fmonjalet** [comment]
Well, you can't stop the timeline yet, but it is easy to add a stop button
(or to replace the play button with a stop button), I can do it before the
merge.

The FIXME I left in the code was about highlighting the time slots; I can't
figure out yet why setting the "fill-opacity"  of the rectangles does
change anything on the display. Any help is welcome here, I'll take a fresh
look at it in the upcoming days.

**Comment by fmonjalet** [comment]
Button added, and the highlighting of the time slots suddenly started working in my browser. Can't know what kind of black javascript magic operates here. Is it fixed on your side too?

**Comment by p-l-** [comment]
Perfect

**Pull request merged**
