### PR TITLE
DyNE basic supporting features v1

### PR DESCRIPTION
**Pull request by dsncia**
This pull request contains the basic features needed by / developed under the scope of the [DyNE ](https://mncd2.ncia.nato.int/ourwork/Pages/WP8.aspx) project, from MN CD2 initiative. Follows a short summary:
- Addition of new APIs to manage remote agents that scan the networks and automatically upload results;
- These API's allow the scheduling and configuration of scans based on the IVREs' own scan templates
- Added Modbus protocol detection to the Bro script
- Added support for the NMAP exclude parameter
- Added new MongoDB collection to store needed scan scheduling and state

Future pull requests will cover:
- Web interface to configure the scans (e.g. scheduling, discovery methods, pre-scanning options, exclusions, etc.)
- Web interface based scan results diffing and timeline visualization
- OpenVAS scans import capability
- New means to identify hosts and group scan results other than by using IP addresses
- Etc.

### CODE REVIEW

**Comment by dsncia** [comment]
@p-l- hi, did you had the time to review this?

**Comment by dsncia** [comment]
Salut Pierre,

Thank you for your reply. To be honest we are a bit disappointed by it but hope to get more clarity from you and find a way forward.

We believe that we have done everything within our possibilities within the last year to match your requirements for adding our code to IVRE. We have even put in the effort to re-engineer our architecture to make it match with your requests. It’s disappointing to hear now you just don’t have the time. 
Please be so kind to let us know if you 
a)	are willing to put effort in reviewing and iterating over proposed enhancements 
b)	will have time available soon to review and iterate over proposed enhancements

Our project funding lasts until the end of this year. It is and has been our stakeholders goal that we contribute our enhancements to IVRE before the end of the project and work side by side with you. After the end of the year we have no funding left to support our efforts, so we need you to make this a success, before the end of the year.

This pull request represents the backend changes we had to do in order to support DyNE distributed agents architecture. If IVRE is not interested in this, it isn’t the changes to the web interface (which are completely accessory) that are going to make the difference. All other PR’s that would come in the future are enhancements / new functionalities that we’re currently working on that aren’t yet ready. They won’t be put forward if IVRE doesn’t have an interest on the capabilities we’re proposing with this request. So this is the most “atomic” we can offer you.

14 days ago, the pull request would have merged cleanly, of course as time goes by the probability of a conflict increases. In any case, that isn’t even a point of contention since we would have to iterate over this pull request improving it accordingly to IVRE team inputs.

Again, please let us know your answers to a) and b) and we ask you to be honest with us, we have spent a lot of time to make this work, but it takes two to tango. If you see a way forward within the given constraints let’s work together and get it done!

**Comment by p-l-** [comment]
I'll be honest, as I have always been.

If this is "the most “atomic” [you] can offer", then I can tell you, this will not be merged.

I understand that you want to get this merged in the project so that you don't have to care about it when your project is over, but that is not how things work. 

I really don't think this should come as a surprise to you, given the discussions we had via e-mail or phone.

**Comment by guinness16oz** [comment]
I think that there is a bit of misunderstanding of meaning of a term 'atomic' pull request. I  think that @dsncia understands it as a "self-contained", so that it offers a complete envisaged enhancement functionality, whereas @p-l-  understands by atomic a small change that does add something without breaking original functionality - it does not have to provide a complete envisioned enhancement functionality, but it should be easy to review.  Can you confirm this? If this is the source of the problem, I think that we can fix it.

Also, although of course we hope that, if accepted, our enhancements will be maintained (this can involve also effort from the original DyNE developers), our main goal is to share our, IMO very useful, work with the community.  This should contribute to improving security posture of governmental and international institutions around the world by making IVRE more suitable for use cases and deployment scenarios that involve highly compartmentalized networks consisting of multiple domains, operating at different security levels and separated by restrictive boundary protection devices and data diodes. Our contributions should also, in our opinion, improve IVRE usability (GUI) and support for enumeration of SCADA and "fragile" devices.
So, we are really looking for a win-win situation, IMO. We just need to make it happen together :-)

**Comment by p-l-** [comment]
I am closing this since it is obvious we will not get to something we can merge anytime soon. I am really sorry for your time.

**Pull request closed without merging**
