### PR TITLE
HTML export

### PR DESCRIPTION
**Pull request by p-l-**
This includes and hence fixes #150.

### CODE REVIEW

**Comment by commial** [comment]
Instead of `ng_init`, maybe we can use the same mechanisms than for `share` option (in `MENU`).

Aside this remark, I completely agree with the rest of the patch

**Comment by p-l-** [comment]
@commial agreed. Is it OK now?

**Comment by commial** [comment]
Yeah, looks good for me!
May you can just add two comment lines describing the option, as for `share`: 
`* - share: (optional) if set to true, add a 'Share' menu. Default is false`

This way, you can omit `false` value, as they are described and already handled thanks to `ng-if`.
 
Otherwise, I'm OK for the merge.

**Comment by p-l-** [comment]
OK, PR updated.

**Pull request merged**
