### PR TITLE
Docker (compose): use ivre/db instead of mongo container

### PR DESCRIPTION
**Pull request by p-l-**
Fixes #810

### CODE REVIEW

**Comment by FireFart** [comment]
Why not use the official mongo:4.2 image (https://hub.docker.com/_/mongo)? I can't see any special configuration in here otherwise other data directories

**Comment by p-l-** [comment]
I would like to use the same config for vagrant & docker-compose.

For now, MongoDB is the only backend in the official image, but that was not the case until very recently (we had Neo4j), and it will probably change in a near future (PostgreSQL and/or Elasticsearch).

**Comment by p-l-** [comment]
However, I do agree it would probably be better to use the official MongoDB image, you are totally right.

I'm going to merge this PR, but I would totally consider a PR using the official MongoDB image (provided it updates both the `docker-compose.yml` and the `Vagrantfile`) and removing the ivre/db image.

BTW, I have created a commit using your name (I hope you don't mind) to add the names to the containers created with `docker-compose.yml`.

Thanks again.

**Comment by p-l-** [comment]
[Travis-CI tests](https://travis-ci.org/p-l-/ivre/builds/604314442)

**Comment by FireFart** [comment]
awesome thanks!

**Pull request merged**
